

export const navArry = [
  {
    
    compname: "ALL JEWELLERY",
    link: "/shop/jewellery",
    categories: [
      { category: "ALL JEWELLERY" },
      { category: "EARRINGS" },
      { category: "PENDANTS" },
      { category: "FINGER RINGS" },
      { category: "MANGALSUTRA" },
      { category: "CHAINS" },
      { category: "NOSE PIN" },
      { category: "NECKLACES" },
      { category: "NECKLACE SET" },
      { category: "BANGLES" },
      { category: "BRACELETS" },
      { category: "PENDANTS & EARRING SET" },
      { category: "GOLD COINS" },
      { category: "GIFT CARD" },
    ],

    gender: [
      { gender: "WOMEN'S JEWELLERY" },
      { gender: "MEN" },
      { gender: "KIDS & TEENS" },
    ],

    priceBrand: [
      { price: "JEWELLERY <25K" },
      { price: "JEWELLERY 25K-50K" },
      { price: "JEWELLERY 50K-1L" },
      { price: "JEWELLERY 1L & ABOVE" },
    ],
    men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    allrings:[],
    collection:[]
  },
  {
    compname: "GOLD",
    link: "/shop/gold",
    categories: [
      { category: "BANGLES" },
      { category: "BRACELETS" },
      { category: "EARRINGS" },
      { category: "GOLD CHAINS" },
      { category: "PENDANTS" },
      { category: "RINGS" },
      { category: "ENGAGEMENT RINGS" },
      { category: "NECKLACES" },
      { category: "NOSE PIN" },
      { category: "KADAS" },
      { category: "MANGALSUTRAS" },
      { category: "JHUMKAS" },
      { category: "HOOP EARRINGS" },
      { category: "STUD EARRINGS" },
      { category: "DROP EARRINGS" },
      { category: "MAANG TIKKA" },
      { category: "NECKLACE SET" },
      { category: "PENDANTS & EARRINGS SETS" },
    ],
    men: [
      { mens: "mens BRACELETS" },
      { mens: "mens CHAINS" },
      { mens: "mens ENGAGEMENT RINGS" },
      { mens: "mens KADAS" },
      { mens: "mens PENDANTS" },
      { mens: "mens RINGS" },
    ], 
    kid: [ 
        {kids:"kids EARRINGS" },
        {kids:"kids ANKLETS"},
        {kids:"kids BANGLES"},
        {kids:"kids BRACELET"},
        {kids:"kids CHAIN"},
        {kids:"kids RINGS"},
    ],
    coins:[
        {coin:"SPECIAL COINS"},
        {coin:"1 GRAM"},
        {coin:"2 GRAM"},
        {coin:"4 GRAM"},
        {coin:"5 GRAM"},
        {coin:"8 GRAM"},
        {coin:"10 GRAM"},
        {coin:"25 GRAM"},
        {coin:"30 GRAM"},
        {coin:"50 GRAM"},
        {coin:"100 GRAM"},
    ],
    metal:[
        {metal:"ROSE"},
        {metal:"WHITE"},
        {metal:"YELLOW"},

    ],
    gender:[],
    priceBrand:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    collection:[],
    allrings:[],
  },
  {
    compname: "DIAMOND",
    link: "/shop/diamond",
    categories: [
        {category:"BANGLES"},
        {category:"BRACELETS"},
        {category:"MANGALSUTRA"},
        {category:"NECKLACE SET"},
        {category:"NECKLACES"},
        {category:"NOSEPINS"},

    ],
    gender: [],
    priceBrand: [
        { price: "diamond <25K" },
        { price: "diamond 25K-50K" },
        { price: "diamond 50K-1L" },
        { price: "diamond 1L & ABOVE" },
      ],
    men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[
        {earrings:"DROP EARRINGS"},
        {earrings:"HOOP EARRINGS"},
        {earrings:"JHUMKAS"},
        {earrings:"STUD EARRINGS"},
    ],
    rings:[
        {rings:"ENGAGEMENT RINGS"},
    ],
    pendants:[
        {pendants:"CASUAL WEAR"},
        {pendants:"DAILY WEAR"},
        {pendants:"PARTY WEAR"},
        {pendants:"PENDANTS & EARRINGS SET"},
        {pendants:"TRADITIONAL"},
    ],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    allrings:[],
    collection:[],


  },
  {
    compname: "EARRINGS",
    link: "/shop/earrings",
    categories: [],
    gender: [],
    priceBrand: [
      { price: "earrings <25K" },
      { price: "earrings 25K-50K" },
      { price: "earrings 50K-1L" },
      { price: "earrings 1L & ABOVE" },
    ],
    men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[
      {style:"ALL EARRINGS"},
      {style:"DROP & DANGLERS"},
      {style:"HOOP & HUGGIES"},
      {style:"JHUMKAS"},
      {style:"STUDS & TOPS"},
    ],
    metal_stone:[
      {metal:"DIAMOND"},
      {metal:"GEMSTONE"},
      {metal:"GOLD"},
      {metal:"PLATINUM METAL"},
      {metal:"ROSE GOLD"},
    ],
    occasion:[
      {occasion:"CASUAL WEAR"},
      {occasion:"MODERN"},
      {occasion:"TRADITIONAL"},
      {occasion:"WEDDING"},
      {occasion:"WORK WEAR"},
    ],
    earringGender:[
      {earringGender:"WOMEN'S EARRINGS"},
      {earringGender:"KIDS & TEENS"}
    ],
    allrings:[],
    collection:[]
  },
  {
    compname: "RINGS",
    link: "/shop/rings",
    categories: [],
    gender: [],
    priceBrand: [
    { price: "rings <25K" },
    { price: "rings 25K-50K" },
    { price: "rings 50K-1L" },
    { price: "rings 1L & ABOVE" },],
    men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[ 
    {metal:"DIAMOND"},
    {metal:"GEMSTONE"},
    {metal:"GOLD"},
    {metal:"ROSE GOLD"},
    {metal:"SOLITAIRE"},
    {metal:"WHITE GOLD"},],
    occasion:[],
    earringGender:[],
    allrings:[
      {allrings:"CASUAL RINGS"},
      {allrings:"COUPLE RINGS"},
      {allrings:"DIAMOND ENGAGEMENT RINGS"},
      {allrings:"ENGAGEMENT RINGS"},
      {allrings:"GOLD ENGAGEMENT RINGS"},
      {allrings:"MEN'S RINGS"},
      {allrings:"PLATINUM ENGAGEMENT RINGS"},
    ],
    collection:[]
  },
  {
    compname: "BESTSELLERS",
    link: "/shop/bestsellers",
    categories: [],
    gender: [],
    priceBrand: [],
    men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    collection:[],
    allrings:[],
  },
  {
    compname: "MIA",
    link: "/shop/mia",
    categories: [],
    gender: [],
    priceBrand: [],
        men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    collection:[],
    allrings:[],
  },
  {
    compname: "COLLECTIONS",
    link: "/shop/collections",
    categories: [],
    gender: [],
    priceBrand: [],
    men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    allrings:[],
    collection:[
      {collection:"STRING IT"},
      {collection:"CELESTE"},
      {collection:"DHAROHAR"},
      {collection:"KAKATIYA"},
      {collection:"JOY OF DRESSING"},
      {collection:"ENGAGEMENT RINGS"},
      {collection:"PRETTY IN PINK"},
      {collection:"TALES OF MYSTIQUE"},
      {collection:"IMPRESSIONS OF NATURE"},
      {collection:"STUNNING EVERY EAR"},
      {collection:"AVEER"},
      {collection:"ALEKHYA"},
      {collection:"CHOZHA"},
      {collection:"DOR"},
      {collection:"RIVAAH X TARUN TAHILIANI"},
    ]
  },
  {
    compname: "WEDDING",
    link: "/shop/wedding",
    categories: [],
    gender: [],
    priceBrand: [],
        men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    collection:[],
    allrings:[],
  },
  {
    compname: "GIFTING",
    link: "/shop/gifting",
    categories: [],
    gender: [],
    priceBrand: [],
        men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    collection:[],
    allrings:[],
  },
  
  {
    compname: "MORE",
    link: "/more",
    categories: [],
    gender: [],
    priceBrand: [],
        men:[],
    kid:[],
    coins:[],
    metal:[],
    earrings:[],
    rings:[],
    pendants:[],
    style:[],
    metal_stone:[],
    occasion:[],
    earringGender:[],
    collection:[],
    allrings:[],
  },
];



// import Alljewellery from "./jewelleryComps/Alljewellery"
// import BestSellers from "./jewelleryComps/BestSellers"
// import Collections from "./jewelleryComps/Collections"
// import Diamond from "./jewelleryComps/Diamond"
// import Earrings from "./jewelleryComps/Earrings"
// import Gifting from "./jewelleryComps/Gifting"
// import Gold from "./jewelleryComps/Gold"
// import GoldenHarvest from "./jewelleryComps/GoldenHarvest"
// import Mia from "./jewelleryComps/Mia"
// import More from "./jewelleryComps/More"
// import Rings from "./jewelleryComps/Rings"
// import Wedding from "./jewelleryComps/Wedding" 

// export const navArry = [
//   {
//     name: <Alljewellery/>,
//     link: "/all-jewellery",
//     categories: [
//       { category: "ALL JEWELLERY" },
//       { category: "EARRINGS" },
//       { category: "PENDANTS" },
//       { category: "FINGER RINGS" },
//       { category: "MANGALSUTRA" },
//       { category: "CHAINS" },
//       { category: "NOSE PIN" },
//       { category: "NECKLACES" },
//       { category: "NECKLACE SET" },
//       { category: "BANGLES" },
//       { category: "BRACELETS" },
//       { category: "PENDANTS & EARRING SET" },
//       { category: "GOLD COINS" },
//       { category: "GIFT CARD" },
//     ],

//     gender: [
//       { gender: "WOMEN'S JEWELLERY" },
//       { gender: "MEN" },
//       { gender: "KIDS & TEENS" },
//     ],

//     priceBrand: [
//       { price: "<25K" },
//       { price: "25K-50K" },
//       { price: "50K-1L" },
//       { price: "1L & ABOVE" },
//     ],
//     men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     allrings:[],
//     collection:[]
//   },
//   {
//     name: <Gold/>,
//     link: "/gold",
//     categories: [
//       { category: "BANGLES" },
//       { category: "BRACELETS" },
//       { category: "EARRINGS" },
//       { category: "GOLD CHAINS" },
//       { category: "PENDANTS" },
//       { category: "RINGS" },
//       { category: "ENGAGEMENT RINGS" },
//       { category: "NECKLACES" },
//       { category: "NOSE PINS" },
//       { category: "KADAS" },
//       { category: "MANGALSUTRAS" },
//       { category: "JHUMKAS" },
//       { category: "HOOP EARRINGS" },
//       { category: "STUD EARRINGS" },
//       { category: "DROP EARRINGS" },
//       { category: "MAANG TIKKA" },
//       { category: "NECKLACE SET" },
//       { category: "PENDANTS & EARRINGS SETS" },
//     ],
//     men: [
//       { mens: "BRACELETS" },
//       { mens: "CHAINS" },
//       { mens: "ENGAGEMENT RINGS " },
//       { mens: "KADAS" },
//       { mens: "PENDANTS" },
//       { mens: "RINGS" },
//     ],
//     kid: [
//         {kids:"EARRINGS" },
//         {kids:"ANKLETS"},
//         {kids:"BANGLES"},
//         {kids:"BRACELET"},
//         {kids:"CHAIN"},
//         {kids:"RINGS"},
//     ],
//     coins:[
//         {coin:"SPECIAL COINS"},
//         {coin:"1 GRAM"},
//         {coin:"2 GRAM"},
//         {coin:"4 GRAM"},
//         {coin:"5 GRAM"},
//         {coin:"8 GRAM"},
//         {coin:"10 GRAM"},
//         {coin:"25 GRAM"},
//         {coin:"30 GRAM"},
//         {coin:"50 GRAM"},
//         {coin:"100 GRAM"},
//     ],
//     metal:[
//         {metal:"ROSE"},
//         {metal:"WHITE"},
//         {metal:"YELLOW"},

//     ],
//     gender:[],
//     priceBrand:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     collection:[],
//     allrings:[],
//   },
//   {
//     name: <Diamond/>,
//     link: "/diamond",
//     categories: [
//         {category:"BANGLES"},
//         {category:"BRACELETS"},
//         {category:"MANGALSUTRA"},
//         {category:"NECKLACE SET"},
//         {category:"NECKLACES"},
//         {category:"NOSEPINS"},

//     ],
//     gender: [],
//     priceBrand: [
//         { price: "<25K" },
//         { price: "25K-50K" },
//         { price: "50K-1L" },
//         { price: "1L & ABOVE" },
//       ],
//     men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[
//         {earrings:"DROP EARRINGS"},
//         {earrings:"HOOP EARRINGS"},
//         {earrings:"JHUMKAS"},
//         {earrings:"STUD EARRINGS"},
//     ],
//     rings:[
//         {rings:"ENGAGEMENT RINGS"},
//     ],
//     pendants:[
//         {pendants:"CASUAL WEAR"},
//         {pendants:"DAILY WEAR"},
//         {pendants:"PARTY WEAR"},
//         {pendants:"PENDANTS & EARRINGS SET"},
//         {pendants:"TRADITIONAL"},
//     ],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     allrings:[],
//     collection:[],


//   },
//   {
//     name: <Earrings/>,
//     link: "/earrings",
//     categories: [],
//     gender: [],
//     priceBrand: [
//       { price: "<25K" },
//       { price: "25K-50K" },
//       { price: "50K-1L" },
//       { price: "1L & ABOVE" },
//     ],
//     men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[
//       {style:"ALL EARRINGS"},
//       {style:"DROP & DANGLERS"},
//       {style:"HOOP & HUGGIES"},
//       {style:"JHUMKAS"},
//       {style:"STUDS & TOPS"},
//     ],
//     metal_stone:[
//       {metal:"DIAMOND"},
//       {metal:"GEMSTONE"},
//       {metal:"GOLD"},
//       {metal:"PLATINUM METAL"},
//       {metal:"ROSE GOLD"},
//     ],
//     occasion:[
//       {occasion:"CASUAL WEAR"},
//       {occasion:"MODERN"},
//       {occasion:"TRADITIONAL"},
//       {occasion:"WEDDING"},
//       {occasion:"WORK WEAR"},
//     ],
//     earringGender:[
//       {earringGender:"WOMEN'S EARRINGS"},
//       {earringGender:"KIDS & TEENS"}
//     ],
//     allrings:[],
//     collection:[]
//   },
//   {
//     name: <Rings/>,
//     link: "/rings",
//     categories: [],
//     gender: [],
//     priceBrand: [
//     { price: "<25K" },
//     { price: "25K-50K" },
//     { price: "50K-1L" },
//     { price: "1L & ABOVE" },],
//     men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[ 
//     {metal:"DIAMOND"},
//     {metal:"GEMSTONE"},
//     {metal:"GOLD"},
//     {metal:"ROSE GOLD"},
//     {metal:"SOLITAIRE"},
//     {metal:"WHITE GOLD"},],
//     occasion:[],
//     earringGender:[],
//     allrings:[
//       {allrings:"CASUAL RINGS"},
//       {allrings:"COUPLE RINGS"},
//       {allrings:"DIAMOND ENGAGEMENT RINGS"},
//       {allrings:"ENGAGEMENT RINGS"},
//       {allrings:"GOLD ENGAGEMENT RINGS"},
//       {allrings:"MEN'S RINGS"},
//       {allrings:"PLATINUM ENGAGEMENT RINGS"},
//     ],
//     collection:[]
//   },
//   {
//     name: <BestSellers/>,
//     link: "/bestsellers",
//     categories: [],
//     gender: [],
//     priceBrand: [],
//     men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     collection:[],
//     allrings:[],
//   },
//   {
//     name: <Mia/>,
//     link: "/mia",
//     categories: [],
//     gender: [],
//     priceBrand: [],
//         men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     collection:[],
//     allrings:[],
//   },
//   {
//     name: <Collections/>,
//     link: "/collections",
//     categories: [],
//     gender: [],
//     priceBrand: [],
//     men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     allrings:[],
//     collection:[
//       {collection:"STRING IT"},
//       {collection:"CELESTE"},
//       {collection:"DHAROHAR"},
//       {collection:"KAKATIYA"},
//       {collection:"JOY OF DRESSING"},
//       {collection:"ENGAGEMENT RINGS"},
//       {collection:"PRETTY IN PINK"},
//       {collection:"TALES OF MYSTIQUE"},
//       {collection:"IMPRESSIONS OF NATURE"},
//       {collection:"STUNNING EVERY EAR"},
//       {collection:"AVEER"},
//       {collection:"ALEKHYA"},
//       {collection:"CHOZHA"},
//       {collection:"DOR"},
//       {collection:"RIVAAH X TARUN TAHILIANI"},
//     ]
//   },
//   {
//     name: <Wedding/>,
//     link: "/wedding",
//     categories: [],
//     gender: [],
//     priceBrand: [],
//         men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     collection:[],
//     allrings:[],
//   },
//   {
//     name: <Gifting/>,
//     link: "/gifting",
//     categories: [],
//     gender: [],
//     priceBrand: [],
//         men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     collection:[],
//     allrings:[],
//   },
//   {
//     name: <GoldenHarvest/>,
//     link: "/golden-harvest",
//     categories: [],
//     gender: [],
//     priceBrand: [],
//         men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     collection:[],
//     allrings:[],
//   },
//   {
//     name: <More/>,
//     link: "/more",
//     categories: [],
//     gender: [],
//     priceBrand: [],
//         men:[],
//     kid:[],
//     coins:[],
//     metal:[],
//     earrings:[],
//     rings:[],
//     pendants:[],
//     style:[],
//     metal_stone:[],
//     occasion:[],
//     earringGender:[],
//     collection:[],
//     allrings:[],
//   },
// ];
